### ISSUE TITLE
Plans & Roadmap

### ISSUE THREAD

**Issue by milindur** [openbmc/sdbusplus#1]
I found this project a few days ago after searching for C++ bindings to D-Bus. Unfortunately I only found Qt (which I do not want to use at the moment), libdbus-c++ (which is incomplete and there are various forks/variants) and libdbus-cpp (which I also cannot use). Besides that the performance of sd-bus is much better than libdbus. So this project looks very promising in creating a full-featured C++ binding to the new/modern sd-bus library. Many thanks for your effort in this project so far.

What are your plans for the further development of this project? Do you, e.g., plan to also add code generation for the client side? How stable is the API of sdbusplus and the generated server stub code?

**Comment by williamspatrick** [comment]
@milindur - Thanks for the inquiry.

A little background first... As you see this repo is currently part of the 'openbmc' project, which is an open source implementation of the BMC firmware that is found in many servers.  Within the project we are using DBus as our IPC mechanism.  I'm working on this, within the context of the OpenBMC project, to enable us to write the DBus applications much faster than using the raw dbus calls themselves.

Our development for the project actually happens out on a public Gerrit server: https://gerrit.openbmc-project.xyz , and we automatically replicate here to Github on merge.  We do use Github for our issue tracking / release planning.

I am currently working on openbmc/openbmc#477 and openbmc/openbmc#478 .  I have code up in Gerrit to generate C++ exception objects and turn them into dbus-errors; I plan to turn them back into (the same) C++ exception on the client side when I get around to that.  

I am also wrapping up support for generated enumerations.  These would be used as C++ enums within code and then turned into strings when they go across the DBus (and turned back into enums in the respective bindings).

The part I'm going to start on after that is the client bindings.  I hope to have that done by the end of this week or end of the month otherwise.  After that I'm going to go back through the sdbusplus base code and make sure all the error cases are handled and turned into exceptions there.

We have developers currently working on application implementations using this library.  In some cases, I'm throwing code at them [in Gerrit] as I write it.  So while it might sound like I'm talking about pretty rapid timelines for these things, it is necessary due to other users of this.

As far as stability, I wouldn't consider it especially stable until we get a little bit of time to use it in real applications.  Since it is based on sdbus, which is itself stable, I expect the sdbusplus portions of it to be fairly stable.  The generated bindings are less so.  I hope to consider it stable by the end of the year.

I've purposefully not been very public about this binding library yet until we get some time to use it and consider it stable.  I do hope it becomes useful to others that do not want to use some of the bulkier bindings like QT or GLib, so I'm certainly interested in your experience if you end up trying to utilize it.  If you need more interactive help or questions, we are also on Freenode IRC #openbmc (my handle is 'stwcx').

**Comment by milindur** [comment]
@williamspatrick Thanks for your response and the background information for this project.

I am considering to use sdbusplus for our project (an embedded communication unit for an inverter), currently it is the most promising candidate. Other bindings are either too heavy (Qt), lack features (dbus-c++) or add an un-needed additional layer of abstraction to D-Bus (Common API C++).

Currently I am evaluating the different features of sdbusplus using your Calculator server example as a starting point. I also implemented a simple client to use the Calculator interface (similar to the generated server code). While testing my server I found an issue with duplicated reply messages on D-Bus (first the correct reply and then an D-Bus error message, both with the same reply_serial), but I have to do further debugging to find the root cause of this. The corresponding C implementation using sd-bus directly works without issues.

Your plans to wrap D-Bus errors in C++ exceptions, support enums and then build the client bindings sounds great. Exception handling as well client bindings are also my top two missing things.

I have to admit that the planned timeline sounds really ambitious. On the other hand there are not many other options to use D-Bus from C++ so I fully understand that the OpenBMC project wants to use these new bindings rather sooner than later. We are in the same boat with our project.

So I would be happy to help you with feedback regarding the library and/or the code generator.

**Comment by williamspatrick** [comment]
Fix for the dual message response is here:

https://gerrit.openbmc-project.xyz/#/c/1186/

I found that yesterday as well and was able to get to the bottom of it. 

You will also find about 20 pending commits in that sequence as well. Those complete the exception and enumeration support.

**Comment by williamspatrick** [comment]
https://gist.github.com/williamspatrick/096e83baed123ba790f31483250a2d70

This is a reference implementation of the 'Calculator' as well. I'll probably check this in under examples.
