### ISSUE TITLE
 ‘meson build‘ error happened

### ISSUE THREAD

**Issue by zzhuang-cancon** [openbmc/sdbusplus#44]
hello， when i use cmd: meson build   to build the "phosphor-state-manager",which i follow the OpenBMC official guide address: https://github.com/openbmc/docs/blob/master/development/web-ui.md
look below:
![image](https://user-images.githubusercontent.com/56622764/79821046-50284f80-83c0-11ea-82d5-6fc576d16948.png)

and then i search everything about 'sdbusplus', and i am here ,i have cloned it  ,but i do not know how to install it.

**Comment by williamspatrick** [comment]
Some of the older openbmc repositories, like `sdbusplus` are still using autotools instead of meson.  The basic flow for one of our autotools repositories is :

```
./bootstrap.sh
./configure
make
make install
```

Having said that, a few pointers here for you.

* `make install` will install into your Linux distribution, which is likely not what you want.  You can set the environment variable `DESTDIR=<some_other_path>` to most tools like make and meson and they will install somewhere else.  (Installing into your Linux distribution will require root permissions).

* You should be able to call `meson` directly rather than that indirect python3 call.  If you can't, you probably have meson installed incorrectly.

* Most developers are not, to my knowledge, compiling free-standing openbmc repositories.  Since OpenBMC is build using Yocto people usually use Yocto-based workflows to do development.  This ensures that all the dependencies they need are satisfied.  The two typical workflows I see are: devtool and Yocto SDK.  You should be able to find information in openbmc/docs on these development workflows.
