### ISSUE TITLE
Unexpected conversion for `_` in filename() 

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/sdbusplus#60]
The filename() is expected to return the DBus object path's "filename", however, it converts underscore `_` unexpectedly.

E.g. the object "/xyz/openbmc_project/software/bios_active"'s `filename()` shall be `bios_active`, but `sdbusplus::message::object_path::filename()` converts it to `bios\xACtive`.

This issue is found in g220a's HW CI after rebasing the code to upstream 06dc92d6f.

**Comment by leiyu-bytedance** [comment]
`sd_bus_path_decode()` is decoding `_ac` to a special character, is it a bug in `sd_bus_path_decode()`?

**Comment by wak-google** [comment]
Yeah, we can't apply sd_bus_path_encode() / decode() to all paths as it changes the meaning of all `_`

**Comment by leiyu-bytedance** [comment]
@edtanous

**Comment by edtanous** [comment]
Yep, this is a problem;  We should probably discuss the solution on discord, because I'm on the fence with what to do about it.  The issue is that underscore has special meaning in dbus paths when they're encoded as the precursor to an escape sequence.  Unfortunately, we also seem to use underscores in the example above where they're not escaped.  In theory bios_active should've been escaped as bios_5Factive, which would've caused this to decode properly.  Instead, it's being put on dbus as-is, which is decoding to the hex code for 0xAC, which is extended ascii for a code that we don't support.  The options I see going forward are:
1. Make sure all paths that want to use underscore are escaped properly using the operator/ apis.  This might be an isolated, or relatively isolated case, in which case this just needs a patch to the service to fix this.
2. Remove all reliance on well known dbus paths, in which case, the failed escaping shouldn't matter.
3. Revert the recent patches, and simply disallow anything but ascii characters on dbus in OpenBMC (which has impacts on what names you can use in sensors for example).
4. Something else?

PS, can you point out the code that's actually broken here?  Ie, what API is using filename() and expecting to get bios_active back out?  I didn't know there was widespread usage of filename() yet.

**Comment by leiyu-bytedance** [comment]
> PS, can you point out the code that's actually broken here? Ie, what API is using filename() and expecting to get bios_active back out? I didn't know there was widespread usage of filename() yet, and the only usage of bios_active that I'm able to find is in intel-ipmi-oem, but I'm unable to find the backend implementation for it. Can you give me some pointers to what code you're looking at?

It is the `bmcweb` https://github.com/openbmc/bmcweb/commit/2dfd18ef that changes the logic of getting the software from manually parsing the string to invoking `filename()`.
The `filename()` was returning `bios_active` before the sdbusplus change's fa0fa3b0, and it breaks the string after fa0fa3b0

**Comment by edtanous** [comment]
> > PS, can you point out the code that's actually broken here? Ie, what API is using filename() and expecting to get bios_active back out? I didn't know there was widespread usage of filename() yet, and the only usage of bios_active that I'm able to find is in intel-ipmi-oem, but I'm unable to find the backend implementation for it. Can you give me some pointers to what code you're looking at?
> 
> It is the `bmcweb` [openbmc/bmcweb@2dfd18e](https://github.com/openbmc/bmcweb/commit/2dfd18ef) that changes the logic of getting the software from manually parsing the string to invoking `filename()`.
> The `filename()` was returning `bios_active` before the sdbusplus change's [fa0fa3b](https://github.com/openbmc/sdbusplus/commit/fa0fa3b0fa5a9d59c37b6edbc53cc21b7c2a16b0), and it breaks the string after [fa0fa3b](https://github.com/openbmc/sdbusplus/commit/fa0fa3b0fa5a9d59c37b6edbc53cc21b7c2a16b0)

No, what is the backend code that is producing an object called "bios_active".  That will need to be corrected to either publish BiosActive or bios_5Factive.

Also, which bmcweb endpoint are you testing with?  The /xyz apis?

**Comment by leiyu-bytedance** [comment]
The `bios_active` comes from https://github.com/openbmc/phosphor-bmc-code-mgmt/commit/6e9fb1d6ec428d1cc05c78b9b394b214b46c0364, but its origin is from Intel-BMC: https://github.com/search?q=org%3AIntel-BMC+bios_active&type=code

**Comment by williamspatrick** [comment]
Unfortunately, we've used snake_case almost everywhere as our preferred dbus naming scheme.  Even our TLDs are snake_case (org/open_power, xyz/openbmc_project).  I'm sort of leaning towards we should rethink how we do escaping and we shouldn't just take in the systemd method.

Looking at my own system, `org.freedesktop.systemd1` and `org.freedesktop.network1` use the systemd manner of escaping but other services do not (`org.freedesktop.login1`, `org.freedesktop.UDisks2`, `org.freedesktop.ColorManager`).  The really odd thing is `network1` actually uses a mixture and `login1` is even a systemd-provided service.

```
$ busctl tree org.freedesktop.login1   
└─/org
  └─/org/freedesktop
    ├─/org/freedesktop/LogControl1
    └─/org/freedesktop/login1
      ├─/org/freedesktop/login1/seat
      │ ├─/org/freedesktop/login1/seat/auto
      │ └─/org/freedesktop/login1/seat/seat0
      ├─/org/freedesktop/login1/session
      │ ├─/org/freedesktop/login1/session/_32
      │ ├─/org/freedesktop/login1/session/_34
      │ └─/org/freedesktop/login1/session/auto
      └─/org/freedesktop/login1/user
        ├─/org/freedesktop/login1/user/_1000
        └─/org/freedesktop/login1/user/self
$ busctl tree org.freedesktop.network1
└─/org
  └─/org/freedesktop
    ├─/org/freedesktop/LogControl1
    └─/org/freedesktop/network1
      ├─/org/freedesktop/network1/link
      │ ├─/org/freedesktop/network1/link/_31
      │ ├─/org/freedesktop/network1/link/_32
      │ └─/org/freedesktop/network1/link/_33
      └─/org/freedesktop/network1/network
        ├─/org/freedesktop/network1/network/_330_2diphone
        ├─/org/freedesktop/network1/network/_350_2ddhcp
        ├─/org/freedesktop/network1/network/_380_2dcontainer_2dve
        ├─/org/freedesktop/network1/network/_380_2dcontainer_2dvz
        ├─/org/freedesktop/network1/network/_380_2dvm_2dvt
        └─/org/freedesktop/network1/network/_380_2dwifi_2dadhoc
```

Notice that in network the `link` hierarchy doesn't use the escape but the `network` does.

**Comment by williamspatrick** [comment]
Alright, correction.  network1 does use the escape.  ascii 31 = '1' and that is the name of the link.  login1 uses it for session maybe, but not user?  My uid is 1000, so _1000 is not escaped.  But the session `_32` has an Id field of `"2"`, so that appears that it does use the escaping.

(At first I couldn't figure out why they decided to escape integers like that, since integers are valid and there are some odd ones like `_330_2diphone` which unescapes to `30-iphone`.  I guess they want to make C-like variable strings with their escaping and you can't start a C variable with an integer?)

**Comment by edtanous** [comment]
> I'm sort of leaning towards we should rethink how we do escaping and we shouldn't just take in the systemd method.

Could you elaborate a little bit on what you're thinking?  Given the number of allowed characters in dbus paths, there aren't that many options that are even possible. 

> At first I couldn't figure out why they decided to escape integers like that

If I remember right, you can't start a dbus path component with an integer (or something like that, the details are fuzzy).

**Comment by williamspatrick** [comment]
> If I remember right, you can't start a dbus path component with an integer (or something like that, the details are fuzzy).

FWIW, object paths segments _can_ start with integers.  Bus Names and Members have this prohibition but not objects.

https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path

**Comment by jonathan-doman** [comment]
For another data point, this issue is breaking a lot of stuff in intel platforms due to the chassis board name containing an underscore which is not escaped by EntityManager. The board name is decoded by bmcweb (into a broken looking name) when generating the ChassisCollection links, but not encoded again when following that link to get the Chassis resource, so the Redfish Chassis is inaccessible.

I don't really follow why we should want to encode all path names. Underscores are perfectly OK in D-Bus paths, and we happen to be using it in a lot of places (since `/xyz/openbmc_project/` suggested that we were supposed to use snake_case), for various functional endpoints and also in sensor names, etc. I would prefer to have the encoding be optional/contextual - although I realize it's harder to manage piecemeal conventions like that.

**Comment by edtanous** [comment]
> For another data point, this issue is breaking a lot of stuff in intel platforms due to the chassis board name containing an underscore which is not escaped by EntityManager. The board name is decoded by bmcweb (into a broken looking name) when generating the ChassisCollection links, but not encoded again when following that link to get the Chassis resource, so the Redfish Chassis is inaccessible.

This sounds like a bug.  I can look into it.  bmcweb should be encoding and decoding at every step.

> 
> I don't really follow why we should want to encode all path names.

Because there are things we want to represent on dbus that aren't just a-z0-9_.  In this specific case, there's a desire to have dashes in sensor names.

> Underscores are perfectly OK in D-Bus paths, and we happen to be using it in a lot of places (since `/xyz/openbmc_project/` suggested that we were supposed to use snake_case), for various functional endpoints and also in sensor names, etc. I would prefer to have the encoding be optional/contextual - although I realize it's harder to manage piecemeal conventions like that.

There's a patchset working on exactly what you want.  The initial half-done stab at this is here:
https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/42512
We also talked about reverting the last encoding patch, which I have yet to push the review for, but I will.

**Comment by Howitzer105mm** [comment]
Ed, 
I'm late to the discussion.
In include/utils/collection.hpp:
                sdbusplus::message::object_path path(object);
                std::string leaf = path.filename();

The invocation of the sdbusplus::message::object_path is the point at which I found the D-Bus Chassis path getting mangled. The object has AC_Baseboard on the way in, and "path" ends up with AC\ufffdseboard coming out.
I submit this since you were only finding the filename() in the ipmi code.

**Comment by edtanous** [comment]
Yep, you're right, filename() is "mangling" the path by applying escaping rules.  James invented his own escaping rules in entity-manager when he found this issue initially (all non-encodable characters become underscores) which doesn't really cover the full range, and causes entity-manager to crash in weird ways if you mess up the json even a little.  That's largely what I'm trying to fix with the encoding and decoding.


https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42628 should makes the Redfish directory structure traversal again, although the names will still be weird, but considering nobody should be using IDs directly, that's less of a concern (something I'm still wanting to fix with the sdbusplus patch though.  I need to figure out how to test it (none of my systems put underscores in chassis names).

**Comment by Howitzer105mm** [comment]
I'd like to understand a bit better...
The github readme indicates sdbusplus is for interfacing to D-Bus using systemd code as the basis.
Is the current situation a result of using the systemd code as the base that is causing the D-Bus path/intf/object parsing issue?
Am I understanding the long term plan is to require changes to existing D-Bus elements to fit systemd rules?
You mention in 42512 that you expect it to be a transitory correction, so I'd like clarification of the long term correction.

**Comment by Howitzer105mm** [comment]
In my first submission to this thread I was pointing out that the name was mangled by sdbusplus::message::object_path path(object); *before* filename() was even called. It was the ::object_path constructor doing the damage to filename() in my investigation of the issue.

**Comment by edtanous** [comment]
I would like to see us move to to systemd naming conventions, which rely on the underscore character and hex codes to escape paths.  I cannot imagine this is everyone's direction, and I'm sure there will be some differing of opinions, but it's something we should definitely discuss.  We've already had issues with daemons that have to interact with systemd services having to do some kind of manual escaping by hand (also getting it wrong).  Also, things like entity-manager invented their own escaping mechanisms (mostly because we didn't know any sort of standard existed at the time).  This is causing issues where certain configs can crash entity-manager because of a bad name in a config file, which is unfortunate because EM is supposed to have a user facing dbus interface.
